Create a prometheus client
CCI-MOC/openshift-usage-scripts pull request #73
Opened 2024-09-13 00:33 UTC by naved001

Part of the refactoring to organize the codebase. This moves the methods to talk to prometheus into a class in its own module.

The unit tests have also been moved to a separate file.

closes https://github.com/CCI-MOC/openshift-usage-scripts/issues/69

2024-09-23 23:58 UTC, knikolla requested changes
Minus the typo seems pretty straightforward and looks good.

2024-09-23 23:58 UTC, knikolla commented on openshift_metrics/prometheus_client.py
> +        self.proemtheus_url = prometheus_url
you have a typo here :)

2024-09-24 01:32 UTC, naved001 commented on openshift_metrics/prometheus_client.py
> +        self.proemtheus_url = prometheus_url
good catch! thanks.

2024-09-24 13:28 UTC, knikolla approved these changes

2024-09-24 13:29 UTC, merged